### ISSUE TITLE
Alpenhorn v2.0 todo list:

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/alpenhorn#14]
List of things we still need to fix up before we can release the new version:

- [ ] Add the update cycle back in
- [ ] Add the auto_import back in.
- [ ] Put in the import cache as a query from the database
- [ ] Rewrite the logging support
- [ ] Write a better README
- [ ] Put in some more overarching documentation
