### ISSUE TITLE
TODO for running on cedar for CHIME

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#140]
This is a tracking issue / to-do list for things that need doing before we can deploy this to cedar for CHIME.  There is no particular order for this list:

- [x] fix concurrency issues with #137
- [x] allow sub-node parallelisation
- [x] io-classing for IO abstraction
- [x] config blob for storage nodes
- [ ] ~node-group edge table~ (Probably not needed to get things running on cedar.)

See also: #136
